import test from 'node:test';
import assert from 'node:assert/strict';
import { makeExamplePlan, calculate, regenerate, togglePin, updateEvent, duplicateEvent, deleteEvent, serialize, normalizePlan, timetableCsv } from '../engine.js';

test('example generates linked schedule, budget and equipment data', () => { const plan = makeExamplePlan(); const result = calculate(plan); assert.equal(result.schedule.length, 4); assert.equal(result.totalBudget, 18050); assert.ok(result.equipment.find(item => item.id === 'pa').usedBy.length); });
test('pinned time survives twenty supported regenerations', () => { let plan = makeExamplePlan(); plan = togglePin(plan, 'act-moss', 'start'); const pinned = plan.events.find(event => event.id === 'act-moss').start; for (let i = 0; i < 20; i++) { const request = ['balanced', 'earlier', 'compact'][i % 3]; const revision = regenerate(plan, request, { force: true }); plan = revision.plan; assert.equal(plan.events.find(event => event.id === 'act-moss').start, pinned); } });
test('identity stays stable across rename, delete and duplicate', () => { let plan = makeExamplePlan(); const original = plan.events[0].id; plan = updateEvent(plan, original, 'name', 'Renamed act'); assert.equal(plan.events[0].id, original); const duplicate = duplicateEvent(plan, original); assert.equal(duplicate.events.filter(event => event.name.startsWith('Renamed act')).length, 2); const removed = deleteEvent(duplicate, original); assert.equal(removed.events.some(event => event.id === original), false); assert.equal(removed.events.some(event => event.name === 'Renamed act copy'), true); });
test('whole revision can be undone from captured before snapshot', () => { const before = makeExamplePlan(); const revision = regenerate(before, 'earlier'); assert.notDeepEqual(revision.plan.events.map(event => event.start), before.events.map(event => event.start)); const restored = normalizePlan(revision.plan.lastRevision.before); assert.deepEqual(restored.events.map(event => event.start), before.events.map(event => event.start)); });
test('portable export round trips and timetable is usable CSV', () => { const plan = makeExamplePlan(); const reopened = normalizePlan(JSON.parse(serialize(plan))); assert.deepEqual(reopened.events.map(event => event.id), plan.events.map(event => event.id)); assert.match(timetableCsv(plan), /"Time","End","Stage","Act"/); });
test('malformed or incompatible imports are rejected', () => { assert.throws(() => normalizePlan({ schemaVersion: 99 }), /Unsupported project version/); assert.throws(() => normalizePlan({ schemaVersion: 1, events: [{ id: 'same', name: 'A', stage: 'Harbour', start: '16:00', duration: 45, audience: 1, budget: 1 }, { id: 'same', name: 'B', stage: 'Pier', start: '17:00', duration: 45, audience: 1, budget: 1 }] }), /duplicate/); });
test('malformed clocks and coerced duplicate IDs are rejected', () => { const base = { name: 'A', stage: 'Harbour', start: '16:00', duration: 45, audience: 1, budget: 1 }; assert.throws(() => normalizePlan({ schemaVersion: 1, events: [{ id: 'a', ...base, start: '99:99' }] }), /invalid field/); assert.throws(() => normalizePlan({ schemaVersion: 1, events: [{ id: 1, ...base }, { id: '1', ...base, name: 'B' }] }), /duplicate/); });
test('portable IDs cannot inject markup and invalid undo snapshots fail atomically', () => { const base = { name: 'A', stage: 'Harbour', start: '16:00', duration: 45, audience: 1, budget: 1 }; assert.throws(() => normalizePlan({ schemaVersion: 1, events: [{ id: 'a"><img src=x>', ...base }] }), /duplicate or missing/); assert.throws(() => normalizePlan({ schemaVersion: 1, events: [{ id: 'a', ...base }], lastRevision: { before: { schemaVersion: 1, events: [{ id: 'bad id', ...base }] }, after: { schemaVersion: 1, events: [{ id: 'a', ...base }] } } }), /Invalid undo history/); });
test('nested undo snapshots require arrays and cannot erase a nonempty plan', () => { const base = { id: 'a', name: 'A', stage: 'Harbour', start: '16:00', duration: 45, audience: 1, budget: 1 }; assert.throws(() => normalizePlan({ schemaVersion: 1, events: [base], lastRevision: { before: { schemaVersion: 1, events: 'bad' }, after: { schemaVersion: 1, events: [base] } } }), /Invalid undo history/); });
test('linked audience, budget and equipment edits round trip through the schema', () => { let plan = makeExamplePlan(); const id = plan.events[0].id; plan = updateEvent(plan, id, 'audience', '777'); plan = updateEvent(plan, id, 'budget', '3333'); plan = updateEvent(plan, id, 'equipment', ['power']); const event = plan.events.find(item => item.id === id); assert.equal(event.audience, 777); assert.equal(event.budget, 3333); assert.deepEqual(event.equipment, ['power']); });
test('regeneration separates same-stage acts with a pinned stage', () => { let plan = makeExamplePlan(); plan.events[1].stage = 'Harbour'; plan.events[1].start = '16:00'; plan = togglePin(plan, plan.events[1].id, 'stage'); const revision = regenerate(plan, 'balanced', { force: true }); assert.equal(revision.requiresResolution, false); assert.ok(calculate(revision.plan).conflicts.every(conflict => conflict.type !== 'stage')); });
